In [1]:
import numpy as np

In [2]:
numbers = np.array(
    [10, 20, 30, 40]
)

print(numbers)

[10 20 30 40]


In [3]:
type(numbers)

numpy.ndarray

In [5]:
arr = np.array(
    [1, 2, 3, 4]
)

In [6]:
arr + 5

array([6, 7, 8, 9])

In [7]:
arr * 2

array([2, 4, 6, 8])

In [8]:
arr ** 2

array([ 1,  4,  9, 16])

In [9]:
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [10]:
data.shape

(2, 3)

In [11]:
expenses = np.array(
    [120, 200, 350, 100]
)

In [12]:
np.sum(expenses)

np.int64(770)

In [13]:
np.mean(expenses)

np.float64(192.5)

In [14]:
np.max(expenses)

np.int64(350)

In [15]:
np.min(expenses)

np.int64(100)